"""Dicts of template names to standardize names."""

word_types = {
    "adjectif": "adj",
    "adj": "adj",
    "adjectif qualificatif": "adj",
    "adverbe": "adv",
    "adv": "adv",
    "adverbe interrogatif": "adv-int",
    "adv-int": "adv-int",
    "adverbe int": "adv-int",
    "adverbe pronominal": "adv-pron",
    "adv-pron": "adv-pron",
    "adverbe pro": "adv-pron",
    "adverbe relatif": "adv-rel",
    "adv-rel": "adv-rel",
    "adverbe rel": "adv-rel",
    "conjonction": "conj",
    "conj": "conj",
    "conjonction de coordination": "conj-coord",
    "conj-coord": "conj-coord",
    "conjonction coo": "conj-coord",
    "copule": "copule",
    "adjectif démonstratif": "adj-dém",
    "adj-dém": "adj-dém",
    "adjectif dém": "adj-dém",
    "déterminant": "det",
    "dét": "det",
    "adjectif exclamatif": "adj-excl",
    "adj-excl": "adj-excl",
    "adjectif exc": "adj-excl",
    "adjectif indéfini": "adj-indéf",
    "adj-indéf": "adj-indéf",
    "adjectif ind": "adj-indéf",
    "adjectif interrogatif": "adj-int",
    "adj-int": "adj-int",
    "adjectif int": "adj-int",
    "adjectif numéral": "adj-num",
    "adj-num": "adj-num",
    "adjectif num": "adj-num",
    "adjectif possessif": "adj-pos",
    "adj-pos": "adj-pos",
    "adjectif pos": "adj-pos",
    "article": "art",
    "art": "art",
    "article défini": "art-déf",
    "art-déf": "art-déf",
    "article déf": "art-déf",
    "article indéfini": "art-indéf",
    "art-indéf": "art-indéf",
    "article ind": "art-indéf",
    "article partitif": "art-part",
    "art-part": "art-part",
    "article par": "art-part",
    "nom": "nom",
    "substantif": "nom",
    "nom commun": "nom",
    "nom de famille": "nom-fam",
    "nom-fam": "nom-fam",
    "patronyme": "patronyme",
    "nom propre": "nom-pr",
    "nom-pr": "nom-pr",
    "nom scientifique": "nom-sciences",
    "nom-sciences": "nom-sciences",
    "nom science": "nom-sciences",
    "nom scient": "nom-sciences",
    "prénom": "prenom",
    "préposition": "prep",
    "prép": "prep",
    "pronom": "pronom",
    "pronom-adjectif": "pronom-adj",
    "pronom démonstratif": "pronom-dém",
    "pronom-dém": "pronom-dém",
    "pronom dém": "pronom-dém",
    "pronom indéfini": "pronom-indéf",
    "pronom-indéf": "pronom-indéf",
    "pronom ind": "pronom-indéf",
    "pronom interrogatif": "pronom-int",
    "pronom-int": "pronom-int",
    "pronom int": "pronom-int",
    "pronom personnel": "pronom-pers",
    "pronom-pers": "pronom-pers",
    "pronom-per": "pronom-pers",
    "pronom réf": "pronom-pers",
    "pronom-réfl": "pronom-pers",
    "pronom réfléchi": "pronom-pers",
    "pronom possessif": "pronom-pos",
    "pronom-pos": "pronom-pos",
    "pronom pos": "pronom-pos",
    "pronom relatif": "pronom-rel",
    "pronom-rel": "pronom-rel",
    "pronom rel": "pronom-rel",
    "verbe": "verb",
    "verb": "verb",
    "verbe pronominal": "verb",
    "verb-pr": "verb",
    "verbe pr": "verb",
    "interjection": "interj",
    "interj": "interj",
    "onomatopée": "onoma",
    "onoma": "onoma",
    "onom": "onoma",
    "affixe": "aff",
    "aff": "aff",
    "circonfixe": "circon",
    "circonf": "circon",
    "circon": "circon",
    "infixe": "inf",
    "inf": "inf",
    "interfixe": "interf",
    "interf": "interf",
    "particule": "part",
    "part": "part",
    "particule numérale": "part-num",
    "part-num": "part-num",
    "particule num": "part-num",
    "postposition": "post",
    "post": "post",
    "postpos": "post",
    "préfixe": "pre",
    "préf": "pre",
    "radical": "radical",
    "rad": "radical",
    "suffixe": "suf",
    "suff": "suf",
    "suf": "suf",
    "pré-verbe": "preverb",
    "pré-nom": "pre-nom",
    "locution": "loc",
    "loc": "loc",
    "locution-phrase": "phr",
    "loc-phr": "phr",
    "proverbe": "prov",
    "prov": "prov",
    "quantificateur": "quantif",
    "quantif": "quantif",
    "variante typographique": "var-typo",
    "var-typo": "var-typo",
    "variante typo": "var-typo",
    "variante par contrainte typographique": "var-typo",
    "lettre": "lettre",
    "symbole": "symb",
    "symb": "symb",
    "classificateur": "class",
    "class": "class",
    "classif": "class",
    "numéral": "numeral",
    "numér": "numeral",
    "num": "numeral",
    "sinogramme": "sinogramme",
    "sinog": "sinogramme",
    "sino": "sinogramme",
    "erreur": "faute",
    "faute": "faute",
    "faute d'orthographe": "faute",
    "faute d’orthographe": "faute",
    "gismu": "gismu",
    "rafsi": "rafsi",
}

word_attributes = {
    "m": "m",
    "masculin": "m",
    "f": "f",
    "féminin": "f",
    "c": "c",
    "fplur": "fplur",
    "fsing": "fsing",
    "fm?": "fm?",
    "fm ?": "fm?",
    "genre": "genre",
    "mf": "mf",
    "masculin et féminin": "mf",
    "mf?": "mf?",
    "mf ?": "mf?",
    "mn ?": "mn?",
    "mplur": "mplur",
    "msing": "msing",
    "n": "n",
    "nplur": "nplur",
    "nsinig": "nsinig",
    "i": "i",
    "intransitif": "i",
    "t": "t",
    "transitif": "t",
}
